rbac:
  name: console-plugin
  # namespace: Default
  roles:
    - createRole: true
      resources:
        - consoles
      scope:
        cluster: true
      apiGroups:
        - "operator.openshift.io"
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
  roleBindings:
  - createBinding: true
    scope:
      cluster: true
    subjects:
      kind: ServiceAccount
      apiGroup: ""
    
# rbacpod:
#   name: console-pod-restart
#   namespace: openshift-console
#   roles:
#     - createRole: true
#       resources:
#         - pods
#       scope:
#         cluster: false
#       apiGroups:
#         - ""
#       verbs:
#         - "get"
#         - "list"
#         - "patch"
#         - "update"
#         - "delete"

#   roleBindings:
#     - createBinding: true
#       scope:
#         cluster: false
#       subjects:
#         kind: ServiceAccount
#         apiGroup: ""