kind: Job
apiVersion: batch/v1
metadata:
  name: activate-console-plugins
  annotations:
    argocd.argoproj.io/sync-wave: "1"
#namespace: openshift-storage
spec:
  template:
    spec:
      containers:
      ## this image is deployed as part of VP so you can run jobs. cli and tools are 2 images that can be used. 
      ##tools has tcpdump,jq,parted,strace utilities
      - name: cli
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest 
        command:
        - /bin/bash
        - -ce
        - |
          values=("mce" "acm" "odf-console")

          # Check if each value is already present in the /spec/plugins array
          for value in "${values[@]}"; do
              if ! oc get consoles.operator.openshift.io cluster -o jsonpath='{.spec.plugins[*]}' | grep -q "\<$value\>"; then
                  # Value not present, so execute the oc patch command to add it
                  echo "Adding $value to /spec/plugins"
                  oc patch consoles.operator.openshift.io cluster --type json -p "[{\"op\": \"add\", \"path\": \"/spec/plugins/-\", \"value\": \"$value\"}]"
              else
                  echo "$value is already present in /spec/plugins"
              fi
          done  
        
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.rbac.name }}-sa
      serviceAccountName: {{ .Values.rbac.name }}-sa
      terminationGracePeriodSeconds: 400