apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    argocd.argoproj.io/instance: jobs
  name: console-pod-restart
  namespace: openshift-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: console-pod-restart-role
subjects:
  - apiGroup: ''
    kind: ServiceAccount
    name: console-pod-restart-sa
    namespace: default