apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    argocd.argoproj.io/instance: jobs
  name: console-pod-restart-role
  namespace: openshift-console
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - delete